### ISSUE TITLE
Initial login fails if API key file does not exist yet

### ISSUE THREAD

**Issue by rvdm** [LeaseWeb/leaseweb-cli#2]
On first run, the login command fails when ~/.lsw does not exist yet. It does correctly ask for the API key when the empty file exists:

```
<rvdm@kitsune:~/code/leaseweb-cli> ./leaseweb login 
Something went wrong
<rvdm@kitsune:~/code/leaseweb-cli> touch ~/.lsw
<rvdm@kitsune:~/code/leaseweb-cli> ./leaseweb login
Enter api key:
Logged in successfully!
<rvdm@kitsune:~/code/leaseweb-cli>
```

**Comment by majidkarimizadeh** [comment]
Hi @rvdm and thanks for reporting the issue! This repo is actively developing, and it'll be fixed in the next update!

**Comment by rvdm** [comment]
Thanks! I'm pretty new to golang, otherwise I'd have given you a PR :) Thanks for making this!
